defaults: &defaults
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: 'myuser'
  password: 'mypassword'
  host: <%= ENV['MYSQL_PORT_3306_TCP_ADDR'] %>
  port: 3306

development:
  <<: *defaults
  database: simpleappdb_dev

test:
  <<: *defaults
  database: simpleappdb_test

